# Generated by Django 4.1.1 on 2022-10-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0007_alter_post_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='entrega1-bocassi/coder_proyecto_final/media/images/'),
        ),
    ]
