# Generated by Django 4.1 on 2022-09-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_desafio_6', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiares',
            name='parentezco',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
